### PR TITLE
Options to run helm with local exec as well

### PR DESCRIPTION
**Pull request by alexproca**
Sometimes helm terraform chart fails. Allow to run the local installed helm with local_exec

### CODE REVIEW

**Comment by murphye** [comment]
I am curious... what do you see as the benefit for having this?

**Comment by alexproca** [comment]
In my case I got the error in the screenshot above with the normal flow (helm being executed via terraform provider). The only way to install gloo was with local-exec helm command.

**Comment by murphye** [comment]
Really weird. The Helm provider worked great for me! 

Can you tell from the error if it's using the correct `kubectl` context?

**Comment by murphye** [comment]
If the Helm Provider is flaky... I would prefer to just remove it completely to keep it simple. Would be nice to know why you have this error, however.

**Comment by alexproca** [comment]
Hmm you may be right. I work with multiple k8s contexts by setting KUBECONFIG variable

**Comment by alexproca** [comment]
But in the shell I used to start terraform I was pointing to the correct KUBECONFIG

**Pull request merged**
